AdministracijaClanova/Controllers/ClanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Api.Database;
using Api.Database.Model;

namespace AdministracijaClanova.Controllers
{
    public class ClanController : Controller
    {
        private readonly ApiContext _context;

        public ClanController(ApiContext context)
        {
            _context = context;
        }

        // GET: Clan
        public async Task<IActionResult> Index()
        {
            var apiContext = _context.Clan.Include(c => c.PodaciSkrbnika);
            return View(await apiContext.ToListAsync());
        }

        // GET: Clan/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clan = await _context.Clan
                .Include(c => c.PodaciSkrbnika)
                .SingleOrDefaultAsync(m => m.ClanId == id);
            if (clan == null)
            {
                return NotFound();
            }

            return View(clan);
        }

        // GET: Clan/Create
        public IActionResult Create()
        {
            ViewData["SkrbnikId"] = new SelectList(_context.PodaciSkrbnika, "SkrbnikId", "Adresa");
            return View();
        }

        // POST: Clan/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClanId,Ime,Prezime,Spol,OIB,Rodendan,Telefon,Email,Adresa,Zvanje,Zanimanje,AkademskaTitula,RegistracijaHVS,SkrbnikId")] Clan clan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SkrbnikId"] = new SelectList(_context.PodaciSkrbnika, "SkrbnikId", "Adresa", clan.SkrbnikId);
            return View(clan);
        }

        // GET: Clan/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clan = await _context.Clan.SingleOrDefaultAsync(m => m.ClanId == id);
            if (clan == null)
            {
                return NotFound();
            }
            ViewData["SkrbnikId"] = new SelectList(_context.PodaciSkrbnika, "SkrbnikId", "Adresa", clan.SkrbnikId);
            return View(clan);
        }

        // POST: Clan/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClanId,Ime,Prezime,Spol,OIB,Rodendan,Telefon,Email,Adresa,Zvanje,Zanimanje,AkademskaTitula,RegistracijaHVS,SkrbnikId")] Clan clan)
        {
            if (id != clan.ClanId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClanExists(clan.ClanId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SkrbnikId"] = new SelectList(_context.PodaciSkrbnika, "SkrbnikId", "Adresa", clan.SkrbnikId);
            return View(clan);
        }

        // GET: Clan/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clan = await _context.Clan
                .Include(c => c.PodaciSkrbnika)
                .SingleOrDefaultAsync(m => m.ClanId == id);
            if (clan == null)
            {
                return NotFound();
            }

            return View(clan);
        }

        // POST: Clan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clan = await _context.Clan.SingleOrDefaultAsync(m => m.ClanId == id);
            _context.Clan.Remove(clan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClanExists(int id)
        {
            return _context.Clan.Any(e => e.ClanId == id);
        }
    }
}

AdministracijaClanova/Controllers/LijecnickiPreglediController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdministracijaClanova;
using Api.Database;
using Api.Database.Model;

namespace AdministracijaClanova.Controllers
{
    public class LijecnickiPreglediController : Controller
    {
        private readonly ApiContext _context;

        public LijecnickiPreglediController(ApiContext context)
        {
            _context = context;
        }

        // GET: LijecnickiPregledi
        public async Task<IActionResult> Index(int? id)
        {
            var lpList = await _context.LijecnickiPregledi.Where(l => l.ClanId == id).ToListAsync();
            var clanObject = await _context.Clan.Where(clan => clan.ClanId == id).SingleOrDefaultAsync();
            ClanLijecnickiPregledi clp = new ClanLijecnickiPregledi { Clan = clanObject, LijecnickiPregledi = lpList };
            return View(clp);
        }

        // GET: LijecnickiPregledi/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lijecnickiPregledi = await _context.LijecnickiPregledi
                .Include(l => l.Clan)
                .SingleOrDefaultAsync(m => m.LijecnickiPreglediId == id);
            if (lijecnickiPregledi == null)
            {
                return NotFound();
            }

            return View(lijecnickiPregledi);
        }

        // GET: LijecnickiPregledi/Create
        public IActionResult Create(int? id)
        {
            ViewData["ClanId"] = new SelectList(_context.Clan, "ClanId", "Ime", id);
            return View(new LijecnickiPregledi { ClanId = (int)id });
        }

        // POST: LijecnickiPregledi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LijecnickiPreglediId,VrijediOd,VrijediDo,ClanId")] LijecnickiPregledi lijecnickiPregledi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lijecnickiPregledi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = lijecnickiPregledi.ClanId });
            }
            ViewData["ClanId"] = new SelectList(_context.Clan, "ClanId", "Ime", lijecnickiPregledi.ClanId);
            return View(lijecnickiPregledi);
        }

        // GET: LijecnickiPregledi/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lijecnickiPregledi = await _context.LijecnickiPregledi.SingleOrDefaultAsync(m => m.LijecnickiPreglediId == id);
            if (lijecnickiPregledi == null)
            {
                return NotFound();
            }
            ViewData["ClanId"] = new SelectList(_context.Clan, "ClanId", "Ime", lijecnickiPregledi.ClanId);
            return View(lijecnickiPregledi);
        }

        // POST: LijecnickiPregledi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LijecnickiPreglediId,VrijediOd,VrijediDo,ClanId")] LijecnickiPregledi lijecnickiPregledi)
        {
            if (id != lijecnickiPregledi.LijecnickiPreglediId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lijecnickiPregledi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LijecnickiPreglediExists(lijecnickiPregledi.LijecnickiPreglediId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = lijecnickiPregledi.ClanId });
            }
            ViewData["ClanId"] = new SelectList(_context.Clan, "ClanId", "Adresa", lijecnickiPregledi.ClanId);
            return View(lijecnickiPregledi);
        }

        // GET: LijecnickiPregledi/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lijecnickiPregledi = await _context.LijecnickiPregledi
                .Include(l => l.Clan)
                .SingleOrDefaultAsync(m => m.LijecnickiPreglediId == id);
            if (lijecnickiPregledi == null)
            {
                return NotFound();
            }

            return View(lijecnickiPregledi);
        }

        // POST: LijecnickiPregledi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lijecnickiPregledi = await _context.LijecnickiPregledi.SingleOrDefaultAsync(m => m.LijecnickiPreglediId == id);
            _context.LijecnickiPregledi.Remove(lijecnickiPregledi);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = lijecnickiPregledi.ClanId });
        }

        private bool LijecnickiPreglediExists(int id)
        {
            return _context.LijecnickiPregledi.Any(e => e.LijecnickiPreglediId == id);
        }
    }
}

AdministracijaClanova/Views/Clan/Create.cshtml
@model  Api.Database.Model.Clan

@{
    ViewData["Title"] = "Novi član";
}

@*<h2>Create</h2>

<h4>Clan</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezime" class="control-label"></label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Spol" class="control-label"></label>
                <input asp-for="Spol" class="form-control" />
                <span asp-validation-for="Spol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OIB" class="control-label"></label>
                <input asp-for="OIB" class="form-control" />
                <span asp-validation-for="OIB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rodendan" class="control-label"></label>
                <input asp-for="Rodendan" class="form-control" />
                <span asp-validation-for="Rodendan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefon" class="control-label"></label>
                <input asp-for="Telefon" class="form-control" />
                <span asp-validation-for="Telefon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresa" class="control-label"></label>
                <input asp-for="Adresa" class="form-control" />
                <span asp-validation-for="Adresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zvanje" class="control-label"></label>
                <input asp-for="Zvanje" class="form-control" />
                <span asp-validation-for="Zvanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zanimanje" class="control-label"></label>
                <input asp-for="Zanimanje" class="form-control" />
                <span asp-validation-for="Zanimanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AkademskaTitula" class="control-label"></label>
                <input asp-for="AkademskaTitula" class="form-control" />
                <span asp-validation-for="AkademskaTitula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistracijaHVS" class="control-label"></label>
                <input asp-for="RegistracijaHVS" class="form-control" />
                <span asp-validation-for="RegistracijaHVS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SkrbnikId" class="control-label"></label>
                <select asp-for="SkrbnikId" class ="form-control" asp-items="ViewBag.SkrbnikId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Povratak</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdministracijaClanova/Views/Clan/Delete.cshtml
@model  Api.Database.Model.Clan

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Clan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Spol)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Spol)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OIB)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OIB)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rodendan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rodendan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Adresa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Zvanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Zvanje)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Zanimanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Zanimanje)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AkademskaTitula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AkademskaTitula)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RegistracijaHVS)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RegistracijaHVS)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PodaciSkrbnika)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PodaciSkrbnika.Adresa)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClanId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AdministracijaClanova/Views/Clan/Details.cshtml
@model  Api.Database.Model.Clan

@{
    ViewData["Title"] = "Detalji";
}

<h2>@Html.DisplayFor(model => model.Ime)  @Html.DisplayFor(model => model.Prezime)</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Spol)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Spol)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OIB)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OIB)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rodendan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rodendan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Adresa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Zvanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Zvanje)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Zanimanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Zanimanje)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AkademskaTitula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AkademskaTitula)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RegistracijaHVS)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RegistracijaHVS)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PodaciSkrbnika)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PodaciSkrbnika.Adresa)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="LijecnickiPregledi" asp-action="Index" asp-route-id="@Model.ClanId">Liječnički pregledi</a> |
    <a asp-action="Edit" asp-route-id="@Model.ClanId">Promjena</a> |
    <a asp-action="Index">Natrag na listu</a>
</div>

AdministracijaClanova/Views/Clan/Edit.cshtml
@model  Api.Database.Model.Clan

@{
    ViewData["Title"] = "Promjena";
}

<h2>Promjena</h2>

<h2>@Html.DisplayFor(model => model.Ime)  @Html.DisplayFor(model => model.Prezime)</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ClanId" />
            <div class="form-group">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezime" class="control-label"></label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Spol" class="control-label"></label>
                <input asp-for="Spol" class="form-control" />
                <span asp-validation-for="Spol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OIB" class="control-label"></label>
                <input asp-for="OIB" class="form-control" />
                <span asp-validation-for="OIB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rodendan" class="control-label"></label>
                <input asp-for="Rodendan" class="form-control" />
                <span asp-validation-for="Rodendan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefon" class="control-label"></label>
                <input asp-for="Telefon" class="form-control" />
                <span asp-validation-for="Telefon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresa" class="control-label"></label>
                <input asp-for="Adresa" class="form-control" />
                <span asp-validation-for="Adresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zvanje" class="control-label"></label>
                <input asp-for="Zvanje" class="form-control" />
                <span asp-validation-for="Zvanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zanimanje" class="control-label"></label>
                <input asp-for="Zanimanje" class="form-control" />
                <span asp-validation-for="Zanimanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AkademskaTitula" class="control-label"></label>
                <input asp-for="AkademskaTitula" class="form-control" />
                <span asp-validation-for="AkademskaTitula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistracijaHVS" class="control-label"></label>
                <input asp-for="RegistracijaHVS" class="form-control" />
                <span asp-validation-for="RegistracijaHVS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SkrbnikId" class="control-label"></label>
                <select asp-for="SkrbnikId" class="form-control" asp-items="ViewBag.SkrbnikId"></select>
                <span asp-validation-for="SkrbnikId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Natrag na listu</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdministracijaClanova/Views/Clan/Index.cshtml
@model IEnumerable<Api.Database.Model.Clan>

@{
    ViewData["Title"] = "Članovi";
}

<p>
    <a asp-action="Create">Novi član</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Ime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Prezime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Spol)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Rodendan)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telefon)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RegistracijaHVS)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.PodaciSkrbnika)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Spol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rodendan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegistracijaHVS)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PodaciSkrbnika.Adresa)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ClanId">Promjena</a> |
                <a asp-action="Details" asp-route-id="@item.ClanId">Detalji</a> |
            </td>
        </tr>
}
    </tbody>
</table>